# go to sleep after one hour (1*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
# Do not display layer changes on the e-ink display, see
# <https://github.com/LOWPROKB/zmk-config-zen-2/issues/2>
CONFIG_CUSTOM_WIDGET_LAYER_STATUS=n
