[ids]
# Internal keyboard
0001:0001
include ids

[global]
chord_timeout = 50
overload_tap_timeout = 300
oneshot_timeout = 400
disable_modifier_guard = 1

[main]
capslock = backspace
leftmeta = layer(alt)
leftalt = timeout(overload(Fn, cancel), 150, layer(Fn))
rightalt = oneshot(altgr)
leftshift = oneshot(shift)
rightshift = backslash

[shift:S]
rightshift = backslash
capslock = backspace
leftalt = timeout(overload(Fn, S-cancel), 150, layer(Fn))
leftshift = timeout(overload(shift, capslock), 150, layer(shift))
# when activated from rightshift, it should be this, but laptop keyboards won't
# be able to do this
# leftshift = layerm(shift, _)

[altgr:G]
leftshift = layerm(shift, kpdot)
rightshift = backslash
capslock = backspace
leftalt = timeout(overload(Fn, A-cancel), 150, layer(Fn))

# Comment this if you don't want to emit symbols at the keycode level
include bindings_symbols

[altgr+shift]
include bindings_symbols

[Fn]
include bindings_fn

[Fn+altgr]
include bindings_media

# Optional tweaks
include optional_backslash_on_rightshift
include optional_enter_on_leftbracket
# include optional_overload_esc_on_fn
include optional_fn_pinky_ctrl
include optional_fn_space_meta
include optional_fn_alt_tab
